# Site settings
title: Aire Libre, un gimnasio libre en Caril칩
email:
description: > # this means to ignore newlines until "baseurl:"
  Publico y gratuito gimnasio al aire libre en Caril칩. Esta abierto 24 horas y esta ubicado en Quebracho y Charata. Construido y mantenido por los vecinos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address: 
  Quebracho y Charata, Caril칩
  #  - line:
  #  - line:
  # Feel free to add more lines here 
telephone:
copyright: Jennifer y Iv치n, los vecinos

# API settings
google_api_key: AIzaSyBePbCnrA1xIgzCZGDUUgwaGlyFWOBvOFk

# Build settings
markdown: kramdown